language: node_js
node_js:
  - '10'
  - '12'
script:
  - npm run lint
  - npm test --coverage
  - npm run build

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
